import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';

// 13.0 split the frontend into public/app.js plus public/js/*.js ES modules.
// Read the aggregate so contract tokens resolve no matter which module owns them.
async function readFrontendJs() {
  const root = new URL('../public/', import.meta.url);
  const parts = [await readFile(new URL('app.js', root), 'utf8')];
  let moduleFiles = [];
  try {
    moduleFiles = (await readdir(new URL('js/', root))).filter((name) => name.endsWith('.js')).sort();
  } catch {
    moduleFiles = [];
  }
  for (const name of moduleFiles) {
    parts.push(await readFile(new URL(`js/${name}`, root), 'utf8'));
  }
  return parts.join('\n');
}

test('frontend exposes the expected operator workflow controls', async () => {
  const html = await readFile(new URL('../public/index.html', import.meta.url), 'utf8');
  const js = await readFrontendJs();

  assert.match(html, /ServerLens/);
  assert.match(html, /data-view="overview"/);
  assert.match(html, /data-view="servers"/);
  assert.match(html, /data-view="server-detail"/);
  assert.match(html, /data-view="analysis"/);
  assert.match(html, /data-view="delivery"/);
  assert.match(html, /data-delivery-tab="inspect"/);
  assert.match(html, /data-delivery-tab="validate"/);
  assert.match(html, /data-delivery-tab="handoff"/);
  assert.match(html, /data-view="reports"/);
  assert.match(html, /data-view="alerts"/);
  assert.match(html, /data-view="ecosystem"/);
  assert.match(html, /data-view="settings"/);
  assert.match(html, /aria-label="Analysis modules"/);
  assert.match(html, /id="analysis-run-builder"/);
  assert.match(html, /aria-label="Analysis run builder"/);
  assert.match(html, /id="analysis-target-cards"/);
  assert.match(html, /data-analysis-preset-card/);
  assert.match(html, /data-analysis-depth-card/);
  assert.match(html, /data-analysis-output-card="page"/);
  assert.match(html, /data-analysis-output-card="markdown"/);
  assert.match(html, /data-analysis-output-card="pdf"/);
  assert.match(html, /id="analysis-evidence-tracker"/);
  assert.match(html, /id="inspection-workspace"/);
  assert.match(html, /aria-label="Authorized Inspection Workspace"/);
  assert.match(html, /id="inspection-step-rail"/);
  assert.match(html, /inspection-step-card/);
  assert.match(html, /id="inspection-evidence-panel"/);
  assert.match(html, /id="inspection-package-button"/);
  assert.match(html, /id="inspection-package-status"/);
  assert.match(html, /id="strategy-workspace"/);
  assert.match(html, /aria-label="10-cycle Strategy Iteration Workspace"/);
  assert.match(html, /id="strategy-iteration-rail"/);
  assert.match(html, /strategy-iteration-card/);
  assert.match(html, /id="strategy-evidence-panel"/);
  assert.match(html, /id="strategy-copy-button"/);
  assert.match(html, /id="strategy-copy-status"/);
  assert.match(html, /id="detail-evidence-tracker"/);
  assert.match(html, /id="report-evidence-tracker"/);
  assert.match(html, /id="server-inspector"/);
  assert.match(html, /id="server-inspector-content"/);
  assert.match(html, /data-inspector-close/);
  assert.match(html, /aria-label="Analysis presets"/);
  assert.match(html, /data-analysis-preset="full-report"/);
  assert.match(html, /data-analysis-preset="security-review"/);
  assert.match(html, /data-analysis-preset="runtime-health"/);
  assert.match(html, /data-analysis-preset="service-ecosystem"/);
  assert.match(html, /aria-label="Analysis depth"/);
  assert.match(html, /id="analysis-target-server"/);
  assert.match(html, /id="analysis-time-range"/);
  assert.match(html, /data-analysis-depth="quick"/);
  assert.match(html, /data-analysis-depth="standard"/);
  assert.match(html, /data-analysis-depth="deep"/);
  assert.match(html, /id="analysis-output-format"/);
  assert.match(html, /id="export-report-button"/);
  assert.match(html, /id="export-pdf-button"/);
  assert.match(html, /id="export-runbook-button"/);
  assert.match(html, /id="status-page-button"/);
  assert.match(html, /id="status-page-preview"/);
  assert.match(html, /id="command-palette-button"/);
  assert.match(html, /id="command-palette"/);
  assert.match(html, /id="command-input"/);
  assert.match(html, /id="command-results"/);
  assert.match(html, /aria-label="Command palette"/);
  assert.match(html, /id="report-history"/);
  assert.match(html, /id="risk-trend"/);
  assert.match(html, /id="report-comparison"/);
  assert.match(html, /id="alert-inbox"/);
  assert.match(html, /id="alert-summary"/);
  assert.match(html, /id="server-search"/);
  assert.match(html, /id="connection-health-map"/);
  assert.match(html, /id="show-archived-servers"/);
  assert.match(html, /id="inventory-export-button"/);
  assert.match(html, /id="inventory-import-button"/);
  assert.match(html, /id="inventory-transfer-json"/);
  assert.match(html, /id="inventory-transfer-status"/);
  assert.match(html, /id="server-submit-button"/);
  assert.match(html, /id="server-cancel-edit"/);
  assert.match(html, /id="settings-form"/);
  assert.match(html, /id="delivery-evidence-button"/);
  assert.match(html, /id="delivery-evidence"/);
  assert.match(html, /id="delivery-readiness-button"/);
  assert.match(html, /id="delivery-readiness"/);
  assert.match(html, /id="handoff-checklist-button"/);
  assert.match(html, /id="handoff-checklist"/);
  assert.match(html, /id="ui-experience-audit-button"/);
  assert.match(html, /id="ui-experience-audit"/);
  assert.match(html, /id="delivery-view"/);
  assert.match(html, /id="release-readiness-workspace"/);
  assert.match(html, /aria-label="Release readiness workspace"/);
  assert.match(html, /data-release-mode-card="operator"/);
  assert.match(html, /data-release-mode-card="client-handoff"/);
  assert.match(html, /data-release-mode-card="incident-review"/);
  assert.match(html, /id="release-readiness-cards"/);
  assert.match(html, /id="release-review-queue"/);
  assert.match(html, /id="release-reference-basis"/);
  assert.match(html, /id="release-safety-ledger"/);
  assert.match(html, /id="ecosystem-view"/);
  assert.match(html, /id="ecosystem-studio"/);
  assert.match(html, /aria-label="Ecosystem quick navigation"/);
  assert.match(html, /id="interaction-swipe-rail"/);
  assert.match(html, /id="eco-resource"/);
  assert.match(html, /id="eco-services"/);
  assert.match(html, /id="eco-containers"/);
  assert.match(html, /id="eco-exposure"/);
  assert.match(html, /id="eco-risk"/);
  assert.match(html, /id="eco-freshness"/);
  assert.match(html, /data-view="ecosystem"/);
  assert.match(html, /retro-v9-shell/);
  assert.match(html, /retro-v10-shell/);
  assert.match(html, /data-component-system="serverlens-v100"/);
  assert.match(html, /id="page-operation-summary"/);
  assert.match(html, /id="page-operation-title"/);
  assert.match(html, /id="page-operation-action"/);
  assert.match(html, /id="page-operation-evidence"/);
  assert.match(html, /id="page-operation-next-step"/);
  assert.match(html, /id="live-monitor-toggle"/);
  assert.match(html, /id="live-monitor-status"/);
  assert.match(html, /id="live-monitor-grid"/);
  assert.match(html, /data-retro-card/);
  assert.match(html, /data-slot="sidebar"/);
  assert.match(html, /data-slot="sidebar-menu-button"/);
  assert.match(html, /data-slot="button"/);
  assert.match(html, /data-slot="badge"/);
  assert.match(html, /data-slot="tabs-list"/);
  assert.match(html, /retro-reference-bar/);
  assert.match(html, /ios-badge/);
  assert.match(html, /ios-button/);
  assert.match(html, /ios-segment/);
  assert.doesNotMatch(html, /ServerLens 1\.0/);
  assert.doesNotMatch(html, /ServerLens 2\.1/);
  assert.doesNotMatch(html, /6\.0 iOS surface/);
  assert.doesNotMatch(html, /ServerLens 6\.0/);
  assert.doesNotMatch(html, /shadcn-v6-shell/);
  assert.doesNotMatch(html, /shadcn controls, Konsta iOS rhythm, local validation\./);
  assert.doesNotMatch(html, /Private build/);
  assert.doesNotMatch(html, /aria-label="Notifications"/);
  assert.doesNotMatch(html, /aria-label="Settings"/);
  assert.match(html, /id="eco-resource"/);
  assert.match(html, /id="eco-services"/);
  assert.match(html, /id="eco-containers"/);
  assert.match(html, /id="eco-exposure"/);
  assert.match(html, /id="eco-risk"/);
  assert.match(html, /id="eco-freshness"/);
  assert.match(html, /id="ecosystem-fleet-summary"/);
  assert.match(html, /data-tactile-card/);
  assert.match(html, /id="action-dock"/);
  assert.match(html, /aria-label="Action Dock"/);
  assert.match(html, /id="action-dock-toggle"/);
  assert.match(html, /data-action-dock-handle/);
  assert.match(html, /id="focus-peek"/);
  assert.match(html, /aria-label="Focus Peek"/);
  assert.match(html, /id="focus-peek-content"/);
  assert.match(html, /id="retention-run-button"/);
  assert.match(html, /id="retention-run-status"/);
  assert.match(html, /name="retentionDays"/);
  assert.match(html, /name="localOnly"/);
  assert.match(html, /name="inboxEnabled"/);
  assert.match(html, /name="alertSeverities"/);
  assert.match(html, /name="aiSummaryEnabled"/);
  assert.match(html, /id="topology-list"/);
  assert.match(html, /id="topology-map"/);
  assert.match(html, /id="service-catalog-list"/);
  assert.match(html, /id="performance-chart"/);
  assert.match(html, /performance-panel/);
  assert.match(html, /id="security-events"/);
  assert.match(html, /id="security-source-review"/);
  assert.match(html, /security-source-review-panel/);
  assert.match(html, /security-events-panel/);
  assert.match(html, /id="risk-event-timeline"/);
  assert.match(html, /id="evidence-appendix"/);
  assert.match(html, /id="container-table"/);
  assert.match(html, /id="port-table"/);
  assert.match(html, /id="firewall-detail"/);
  assert.match(html, /name="port"/);
  assert.match(html, /name="authType"/);
  assert.match(html, /name="mode"/);
  assert.match(html, /name="username"/);
  assert.match(html, /name="keyPath"/);
  assert.match(html, /name="group"/);
  assert.match(html, /name="tags"/);
  assert.match(js, /health/);
  assert.match(js, /security/);
  assert.match(js, /runtime/);
  assert.match(js, /ecosystem/);
  assert.match(js, /logs/);
  assert.match(js, /network/);
  assert.match(js, /performance/);
  assert.match(js, /analysis-jobs/);
  assert.match(js, /markdown/);
  assert.match(js, /\/print/);
  assert.match(js, /activeAnalysisDepth/);
  assert.match(js, /inspectorOpen/);
  assert.match(js, /inspectorServerId/);
  assert.match(js, /analysisRunning/);
  assert.match(js, /releaseMode/);
  assert.match(js, /actionDockOpen/);
  assert.match(js, /liveMonitoring/);
  assert.match(js, /refreshInFlight/);
  assert.match(js, /setInterval/);
  assert.match(js, /renderLiveMonitor/);
  assert.match(js, /actionDockSnap/);
  assert.match(js, /focusPeekOpen/);
  assert.match(js, /focusPeekContext/);
  assert.match(js, /inspectionWorkspace/);
  assert.match(js, /activeInspectionStep/);
  assert.match(js, /inspectionPackageStatus/);
  assert.match(js, /strategyWorkspace/);
  assert.match(js, /activeStrategyIteration/);
  assert.match(js, /strategyCopyStatus/);
  assert.match(js, /deliveryEvidenceManifest/);
  assert.match(js, /releaseModeCopy/);
  assert.match(js, /renderReleaseWorkspace/);
  assert.match(js, /releaseReadinessCards/);
  assert.match(js, /releaseReviewQueue/);
  assert.match(js, /releaseReferenceBasis/);
  assert.match(js, /releaseSafetyLedger/);
  assert.match(js, /data-release-mode-card/);
  assert.match(js, /renderEcosystem/);
  assert.match(js, /\/api\/ecosystem\/overview/);
  assert.match(js, /state\.ecosystem/);
  assert.match(js, /renderInspectionWorkspace/);
  assert.match(js, /inspectionStepItems/);
  assert.match(js, /setInspectionStep/);
  assert.match(js, /copyInspectionPackageSummary/);
  assert.match(js, /\/api\/delivery\/inspection/);
  assert.match(js, /renderStrategyWorkspace/);
  assert.match(js, /strategyIterationItems/);
  assert.match(js, /setStrategyIteration/);
  assert.match(js, /copyStrategySummary/);
  assert.match(js, /\/api\/delivery\/strategy/);
  assert.match(js, /renderEcosystem/);
  assert.match(js, /\/api\/ecosystem\/overview/);
  assert.match(js, /state\.ecosystem/);
  assert.match(js, /renderActionDock/);
  assert.match(js, /renderFocusPeek/);
  assert.match(js, /bindTactileCards/);
  assert.match(js, /bindIosInteractions/);
  assert.match(js, /updateIosPointer/);
  assert.match(js, /resetIosPointer/);
  assert.match(js, /ios-interactive/);
  assert.match(js, /bindSwipeRails/);
  assert.match(js, /updateRailEdgeState/);
  assert.match(js, /ios-snap-rail/);
  assert.match(js, /openActionDock/);
  assert.match(js, /closeActionDock/);
  assert.match(js, /toggleActionDockSnap/);
  assert.match(js, /openFocusPeek/);
  assert.match(js, /data-action-dock-command/);
  assert.match(js, /data-focus-peek/);
  assert.match(js, /\/api\/delivery\/evidence/);
  assert.match(js, /activeAnalysisPreset/);
  assert.match(js, /analysisPresets/);
  assert.match(js, /applyAnalysisPreset/);
  assert.match(js, /activeAnalysisTimeRange/);
  assert.match(js, /analysisTargetSelect/);
  assert.match(js, /timeRange:\s*state\.activeAnalysisTimeRange/);
  assert.match(js, /preset:\s*state\.activeAnalysisPreset/);
  assert.match(js, /activeOutputFormat/);
  assert.match(js, /renderAnalysisTargetCards/);
  assert.match(js, /data-analysis-target-card/);
  assert.match(js, /renderEvidenceTrackers/);
  assert.match(js, /evidenceTrackerMarkup/);
  assert.match(js, /openServerInspector/);
  assert.match(js, /renderServerInspector/);
  assert.match(js, /data-open-inspector/);
  assert.match(js, /depth:\s*state\.activeAnalysisDepth/);
  assert.match(js, /copyMarkdownReport/);
  assert.match(js, /openPrintReport/);
  assert.match(js, /copyServerRunbook/);
  assert.match(js, /\/runbook\/markdown/);
  assert.match(js, /retentionDays/);
  assert.match(js, /\/api\/maintenance\/retention/);
  assert.match(js, /retentionRunButton/);
  assert.match(js, /retentionRunStatus/);
  assert.match(js, /\/api\/delivery\/evidence/);
  assert.match(js, /renderDeliveryEvidence/);
  assert.match(js, /\/api\/delivery\/readiness/);
  assert.match(js, /renderDeliveryReadiness/);
  assert.match(js, /deliveryReadinessButton/);
  assert.match(js, /\/api\/delivery\/checklist/);
  assert.match(js, /renderHandoffChecklist/);
  assert.match(js, /handoffChecklistButton/);
  assert.match(js, /\/api\/delivery\/ui-audit/);
  assert.match(js, /renderUiExperienceAudit/);
  assert.match(js, /uiExperienceAuditButton/);
  assert.match(js, /local-ui-experience-audit/);
  assert.match(js, /localOnly/);
  assert.match(js, /aiSummary/);
  assert.match(js, /\/api\/servers/);
  assert.match(js, /test-connection/);
  assert.match(js, /connection-status/);
  assert.match(js, /renderConnectionHealthMap/);
  assert.match(js, /pageExperienceModel/);
  assert.match(js, /renderPageOperationSummary/);
  assert.match(js, /page-operation-summary/);
  assert.match(js, /connection-stage-list/);
  assert.match(js, /connection-next-actions/);
  assert.match(js, /data-connection-next-step/);
  assert.match(js, /editingServerId/);
  assert.match(js, /serverPayloadFromForm/);
  assert.match(js, /loadServerForm/);
  assert.match(js, /resetServerForm/);
  assert.match(js, /data-edit-server/);
  assert.match(js, /data-archive-server/);
  assert.match(js, /data-restore-server/);
  assert.match(js, /activeServers/);
  assert.match(js, /\/api\/servers\/all/);
  assert.match(js, /\/api\/servers\/export/);
  assert.match(js, /\/api\/servers\/import/);
  assert.match(js, /inventoryTransferJson/);
  assert.match(js, /Save Server/);
  assert.match(js, /username/);
  assert.match(js, /keyPath/);
  assert.match(js, /server\.mode/);
  assert.match(js, /renderPerformancePanel/);
  assert.match(js, /renderEcosystem/);
  assert.match(js, /healthCell\('Server'/);
  assert.match(js, /healthCell\('Disk'/);
  assert.match(js, /health-cell-label/);
  assert.match(js, /pressureClass/);
  assert.match(js, /networkRxMbps/);
  assert.match(js, /diskReadMbps/);
  assert.match(js, /diskWriteMbps/);
  assert.match(js, /ioWaitPercent/);
  assert.match(js, /renderSecurityEvents/);
  assert.match(js, /renderRiskEventTimeline/);
  assert.match(js, /renderSecuritySourceReview/);
  assert.match(js, /securitySourceReview/);
  assert.match(js, /local-security-source-review/);
  assert.match(js, /riskEventTimeline/);
  assert.match(js, /local-evidence-timeline/);
  assert.match(js, /failedSshLogins10m/);
  assert.match(js, /suspiciousConnections/);
  assert.match(js, /exposedHighRiskPorts/);
  assert.match(js, /renderTopology/);
  assert.match(js, /renderTopologyMap/);
  assert.match(js, /topologyMap/);
  assert.match(js, /renderServiceCatalog/);
  assert.match(js, /serviceCatalog/);
  assert.match(js, /renderRuntimeInventory/);
  assert.match(js, /container-table/);
  assert.match(js, /firewall\.allowedPublicPorts/);
  assert.match(js, /service-topology/);
  assert.match(js, /\/api\/reports\/summary/);
  assert.match(js, /\/api\/status-page/);
  assert.match(js, /renderStatusPagePreview/);
  assert.match(js, /statusPageButton/);
  assert.match(js, /\/api\/alerts/);
  assert.match(js, /acknowledgeAlert/);
  assert.match(js, /renderAlertsInbox/);
  assert.match(js, /alert-inbox/);
  assert.match(js, /command-list/);
  assert.match(js, /finding\.commands/);
  assert.match(js, /api\(`\/api\/reports\/\$\{item\.dataset\.reportId\}`\)/);
  assert.match(js, /selectedReportId/);
  assert.match(js, /renderReportCenter/);
  assert.match(js, /renderExecutiveSummary/);
  assert.match(js, /renderRemediationPlan/);
  assert.match(js, /renderEvidenceAppendix/);
  assert.match(js, /evidenceAppendix/);
  assert.match(js, /local-redacted-evidence/);
  assert.match(js, /executiveSummary/);
  assert.match(js, /remediationPlan/);
  assert.match(js, /remediation-checklist/);
  assert.match(js, /remediation-phase/);
  assert.match(js, /report-history/);
  assert.match(js, /history-item is-selected/);
  assert.match(js, /aria-label="Open report/);
  assert.match(js, /exportPdfButton/);
  assert.match(js, /openCommandPalette/);
  assert.match(js, /renderCommandPalette/);
  assert.match(js, /commandItems/);
  assert.match(js, /runCommand/);
  assert.match(js, /hydrateRetroUiPrimitives/);
  assert.match(js, /dataset\.retroCard/);
  assert.match(js, /dataset\.retroButton/);
  assert.match(js, /dataset\.retroInput/);
  assert.match(js, /commandActiveIndex/);
  assert.match(js, /setCommandActiveIndex/);
  assert.match(js, /data-selected/);
  assert.match(js, /aria-selected/);
  assert.match(js, /ArrowDown/);
  assert.match(js, /ArrowUp/);
  assert.match(js, /ctrlKey/);
  assert.match(js, /metaKey/);
  assert.match(js, /data-command-index/);
  assert.doesNotMatch(js, /Manual module mix/);
  assert.doesNotMatch(js, /Complete handoff review/);
  assert.doesNotMatch(js, /Defensive evidence only/);
  assert.match(js, /data-slot="command-item"/);
  assert.match(js, /shortcut:\s*'A'/);
  assert.match(js, /compactEvidenceLabel/);
  assert.match(js, /compactStatusLabel/);
  assert.match(js, /\.slice\(0, 4\)\.map/);
  const actionDockRenderer = js.slice(js.indexOf('function renderActionDock()'), js.indexOf('function actionDockCommands()'));
  assert.ok(!actionDockRenderer.includes('<small>${escapeHtml(command.detail)}</small>'));
  assert.ok(!js.includes("title: '2.1 flow'"));
});

test('frontend declares the 15.0 accessibility contracts', async () => {
  const html = await readFile(new URL('../public/index.html', import.meta.url), 'utf8');
  const css = await readFile(new URL('../public/styles.css', import.meta.url), 'utf8');

  // Skip link and main landmark.
  assert.match(html, /class="skip-link" href="#main-content"/);
  assert.match(html, /id="main-content"/);
  assert.match(css, /\.skip-link/);

  // Delivery workspace is a real ARIA tab set.
  assert.match(html, /role="tablist"/);
  assert.match(html, /id="delivery-tab-button-inspect"[^>]*role="tab"/);
  assert.match(html, /id="delivery-tab-inspect"[^>]*role="tabpanel"/);
  assert.match(html, /aria-controls="delivery-tab-inspect"/);

  // Live regions on dynamic status surfaces.
  assert.match(html, /id="live-monitor-status"[^>]*aria-live="polite"/);
  assert.match(html, /id="page-operation-summary"[^>]*aria-live="polite"/);

  // Reduced-motion support remains declared.
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)/);
});

test('design system uses ServerLens 10 page operation tokens without banned effects', async () => {
  const css = await readFile(new URL('../public/styles.css', import.meta.url), 'utf8');

  assert.match(css, /--surface:/);
  assert.match(css, /--accent:/);
  assert.match(css, /--font-retro-display:/);
  assert.match(css, /Archivo Black/);
  assert.match(css, /Space Grotesk/);
  assert.match(css, /--retro-paper:/);
  assert.match(css, /--retro-ink:/);
  assert.match(css, /--retro-yellow:/);
  assert.match(css, /--retro-blue:/);
  assert.match(css, /--retro-green:/);
  assert.match(css, /--retro-red:/);
  assert.match(css, /--retro-shadow:\s*6px 6px 0 var\(--retro-line\)/);
  assert.match(css, /\.retro-v9-shell \[data-slot="button"\]/);
  assert.match(css, /\.retro-v9-shell \[data-slot="badge"\]/);
  assert.match(css, /\.retro-v9-shell \[data-retro-card\]/);
  assert.match(css, /\.retro-v9-shell input/);
  assert.match(css, /\.retro-v9-shell \.workspace/);
  assert.match(css, /\.retro-v9-shell \.live-monitor-grid/);
  assert.match(css, /ServerLens 9\.0 clarity pass/);
  assert.match(css, /ServerLens 9\.0 page-wide layout pass/);
  assert.match(css, /grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\)/);
  assert.match(css, /\.retro-v9-shell \.view\.is-visible/);
  assert.match(css, /\.retro-v9-shell \.server-form,\s*\n\.retro-v9-shell \.settings-form/);
  assert.match(css, /\.retro-v9-shell \.inspection-step-rail/);
  assert.match(css, /\.retro-v9-shell \.live-pulse/);
  assert.match(css, /\.retro-v9-shell \.command-result/);
  assert.match(css, /\.retro-v9-shell \.action-dock-panel/);
  assert.match(css, /\.retro-v10-shell \.page-operation-summary/);
  assert.match(css, /\.page-operation-evidence/);
  assert.match(css, /\.page-operation-next-step/);
  assert.match(css, /overflow-y:\s*auto/);
  assert.match(css, /overflow-wrap:\s*anywhere/);
  assert.match(css, /white-space:\s*normal/);
  assert.match(css, /translate\(3px,\s*3px\)/);
  assert.match(css, /--signal/);
  assert.match(css, /scroll-behavior:\s*smooth/);
  assert.match(css, /overscroll-behavior/);
  assert.match(css, /-webkit-overflow-scrolling:\s*touch/);
  assert.match(css, /\.health-cell-label/);
  assert.match(css, /\.health-cell-value/);
  const mobileHealthStyles = css.slice(css.indexOf('@media (max-width: 900px)'));
  assert.match(mobileHealthStyles, /\.health-row \.health-cell-label/);
  assert.match(mobileHealthStyles, /\.health-row > span/);
  assert.match(mobileHealthStyles, /letter-spacing:\s*0\.06em/);
  assert.match(css, /\.skeleton/);
  assert.match(css, /:focus-visible/);
  assert.match(css, /\.command-palette/);
  assert.match(css, /\.command-panel/);
  assert.match(css, /\.command-results/);
  assert.match(css, /\.command-result/);
  assert.match(css, /\.performance-panel/);
  assert.match(css, /\.performance-chart/);
  assert.match(css, /\.spark-bars/);
  assert.match(css, /\.pressure-meter/);
  assert.match(css, /\.security-events/);
  assert.match(css, /\.security-source-review/);
  assert.match(css, /\.security-source-list/);
  assert.match(css, /\.security-source-row/);
  assert.match(css, /\.security-signal-grid/);
  assert.match(css, /\.security-connection-list/);
  assert.match(css, /\.risk-event-timeline/);
  assert.match(css, /\.risk-event-row/);
  assert.match(css, /\.risk-event-rail/);
  assert.match(css, /\.evidence-appendix/);
  assert.match(css, /\.evidence-appendix-row/);
  assert.match(css, /\.evidence-redaction-note/);
  assert.match(css, /\.analysis-presets/);
  assert.match(css, /\.analysis-run-builder/);
  assert.match(css, /\.analysis-choice-card/);
  assert.match(css, /\.target-card-grid/);
  assert.match(css, /\.evidence-tracker/);
  assert.match(css, /\.evidence-step/);
  assert.match(css, /\.server-inspector/);
  assert.match(css, /\.inspector-panel/);
  assert.match(css, /\.inspector-summary/);
  assert.match(css, /\.health-row-button/);
  assert.match(css, /\.preset-button/);
  assert.match(css, /\.server-item\.is-archived/);
  assert.match(css, /\.connection-health-map/);
  assert.match(css, /\.connection-stage-list/);
  assert.match(css, /\.connection-next-actions/);
  assert.match(css, /\.connection-pulse-card/);
  assert.match(css, /\.status-badge/);
  assert.match(css, /\.toggle-row/);
  assert.match(css, /--retro-paper/);
  assert.match(css, /--retro-ink/);
  assert.match(css, /--signal/);
  assert.match(css, /\.retro-v9-shell/);
  assert.match(css, /\.retro-reference-bar/);
  assert.match(css, /\.ios-badge/);
  assert.match(css, /\.ios-panel/);
  assert.match(css, /\.ios-list/);
  assert.match(css, /\.ios-meter/);
  assert.match(css, /\.ios-field/);
  assert.match(css, /\.ios-input/);
  assert.match(css, /\.ios-select/);
  assert.match(css, /\.ios-button/);
  assert.match(css, /\.delivery-evidence-panel/);
  assert.match(css, /\.delivery-readiness-panel/);
  assert.match(css, /\.handoff-checklist-panel/);
  assert.match(css, /\.ui-experience-audit-panel/);
  assert.match(css, /\.ui-audit-check-list/);
  assert.match(css, /\.ui-audit-check/);
  assert.match(css, /\.ui-audit-check\.pass/);
  assert.match(css, /\.handoff-checklist/);
  assert.match(css, /\.handoff-step/);
  assert.match(css, /\.handoff-step\.ready/);
  assert.match(css, /\.handoff-step\.review/);
  assert.match(css, /\.handoff-step\.blocked/);
  assert.match(css, /\.strategy-workspace/);
  assert.match(css, /\.strategy-iteration-rail/);
  assert.match(css, /\.strategy-iteration-card/);
  assert.match(css, /\.strategy-iteration-card\.is-selected/);
  assert.match(css, /\.strategy-evidence-panel/);
  assert.match(css, /\.strategy-reference-grid/);
  assert.match(css, /\.release-workspace/);
  assert.match(css, /\.release-mode-strip/);
  assert.match(css, /\.release-mode-card/);
  assert.match(css, /\.release-mode-card\.is-selected/);
  assert.match(css, /\.release-summary-grid/);
  assert.match(css, /\.release-readiness-card/);
  assert.match(css, /\.release-review-queue/);
  assert.match(css, /\.release-reference-grid/);
  assert.match(css, /\.release-safety-ledger/);
  assert.match(css, /\.release-action-row/);
  assert.match(css, /\.ecosystem-hero/);
  assert.match(css, /\.ecosystem-grid/);
  assert.match(css, /\.ecosystem-panel/);
  assert.match(css, /\.eco-metric-row/);
  assert.match(css, /\.eco-role-row/);
  assert.match(css, /\.eco-stat-grid/);
  assert.match(css, /\.eco-stat/);
  assert.match(css, /\.eco-hotspot/);
  assert.match(css, /\.eco-fresh-row/);
  assert.match(css, /\.eco-trend/);
  assert.match(css, /\.interaction-swipe-rail/);
  assert.match(css, /scroll-snap-type:\s*x mandatory/);
  assert.match(css, /--ios-material/);
  assert.match(css, /--ios-spring/);
  assert.match(css, /\.ios-interactive/);
  assert.match(css, /\.ios-interactive\.is-pressed/);
  assert.match(css, /\.ios-snap-rail/);
  assert.match(css, /\.ios-snap-rail\.is-scrollable/);
  assert.match(css, /\.tactile-card/);
  assert.match(css, /\.tactile-card\.is-pressed/);
  assert.match(css, /\.action-dock/);
  assert.match(css, /\.action-dock\.is-open/);
  assert.match(css, /\.action-dock\.is-expanded/);
  assert.match(css, /\.action-dock\.is-compact/);
  assert.match(css, /\.action-dock-handle/);
  assert.match(css, /\.retro-v9-shell \.dock-command-grid/);
  assert.match(css, /grid-template-columns:\s*72px minmax\(0, 1fr\) 28px/);
  assert.match(css, /max-height:\s*min\(64svh, 560px\)/);
  assert.match(css, /\.focus-peek/);
  assert.match(css, /\.focus-peek\.is-open/);
  assert.match(css, /\.dock-command-grid/);
  assert.match(css, /cubic-bezier\(0\.22,\s*1,\s*0\.36,\s*1\)/);
  assert.match(css, /\.readiness-summary/);
  assert.match(css, /\.readiness-check/);
  assert.match(css, /\.readiness-check\.pass/);
  assert.match(css, /\.readiness-check\.warn/);
  assert.match(css, /\.readiness-check\.fail/);
  assert.match(css, /\.retention-maintenance-panel/);
  assert.match(css, /\.maintenance-result/);
  assert.match(css, /\.status-page-panel/);
  assert.match(css, /\.status-service-row/);
  assert.match(css, /\.service-catalog-list/);
  assert.match(css, /\.topology-map/);
  assert.match(css, /\.topology-node/);
  assert.match(css, /\.topology-edge/);
  assert.match(css, /\.topology-node\.high/);
  assert.match(css, /\.topology-node\.critical/);
  assert.match(css, /\.service-catalog-row/);
  assert.match(css, /\.role-badge/);
  assert.match(css, /\.executive-summary/);
  assert.match(css, /\.remediation-checklist/);
  assert.match(css, /\.remediation-phase/);
  assert.match(css, /\.remediation-item/);
  assert.match(css, /\.remediation-meta/);
  assert.match(css, /\.summary-columns/);
  assert.match(css, /\.inventory-transfer/);
  assert.match(css, /\.transfer-actions/);
  assert.doesNotMatch(css, /#000(?:;|\s)/);
  assert.doesNotMatch(css, /#fff(?:;|\s)/);
  assert.doesNotMatch(css, /background-clip:\s*text/);
  assert.doesNotMatch(css, /border-left:\s*[2-9]px/);
});
